# Generated by Django 2.2.2 on 2019-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_auto_20190619_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
