# Generated by Django 2.2.2 on 2019-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0005_laptop_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='category_name',
            field=models.CharField(default='Laptop', max_length=120),
        ),
    ]
