# Generated by Django 2.2.2 on 2019-06-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0006_auto_20190625_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
