# Generated by Django 2.2.2 on 2019-06-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0007_auto_20190626_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='category_name',
        ),
    ]
