# Generated by Django 2.2.2 on 2019-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0008_remove_laptop_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='laptop',
            name='category_name',
            field=models.CharField(default='Laptop', max_length=120),
        ),
    ]
